version: '3'
services:
    web:
        image: runner668/php-apache:7.4
        container_name: web
        restart: always
        user: application
        environment:
          - WEB_ALIAS_DOMAIN=local.domain.com
          - WEB_DOCUMENT_ROOT=/app/pub
          - PHP_DATE_TIMEZONE=EST
          - PHP_DISPLAY_ERRORS=1
          - PHP_MEMORY_LIMIT=-1
          - PHP_MAX_EXECUTION_TIME=300
          - PHP_POST_MAX_SIZE=500M
          - PHP_UPLOAD_MAX_FILESIZE=1024M
          - PHP_DEBUGGER=xdebug
        volumes:
          - /Users/blowhorn/work/workspaces/magento:/app:cached
        ports:
          - "80:80"
          - "443:443"
          - "32823:22"
        links:
          - mysql
    mysql:
        image: mariadb:10.4
        container_name: mysql
        restart: always
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=magento
        volumes:
          - db-data:/var/lib/mysql
#    phpmyadmin:
#        container_name: phpmyadmin
#        restart: always
#        image: phpmyadmin/phpmyadmin:latest
#        environment:
#          - MYSQL_ROOT_PASSWORD=root
#          - PMA_USER=root
#          - PMA_PASSWORD=root
#        ports:
#          - "8080:80"
#        links:
#          - mysql:db
#        depends_on:
#          - mysql
    elasticsearch:
        container_name: elasticsearch
        restart: always
        image: markoshust/magento-elasticsearch:7.9.3-1
        ports:
          - "9200:9200"
          - "9300:9300"
        environment:
          - "discovery.type=single-node"
          - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
          - "cluster.routing.allocation.disk.threshold_enabled=false"
          - "index.blocks.read_only_allow_delete"
volumes:
    db-data:
        external: false
